### ISSUE TITLE
API for uploading Images

### ISSUE THREAD

**Issue by aqelkp** [The-WebOps-Club/erp-2016#12]
Create an API for saving profile pic

**Comment by deepakpadamata** [comment]
`POST` to `/api/uploads`
Request Body:
`file`: pic input
Response:
`fileId`: ID of the file as in out db

`GET` to `/api/uploads/:id/:filename`
Request Params:
`id`: ID the the file as returned when file was uploaded
`filename`: Any custom file name you wish to set, in this case you can make it profile.jpg

Next:
Update the profilePic field of the user Model with the File Id of the Image. (What whould you say about putting the full link to the person's profile pic?)

**Comment by aqelkp** [comment]
@deepakpadamata What is that fileId?
You should send the link to pic in response in all cases where there is a need for pictures.

**Comment by deepakpadamata** [comment]
Well, it is a multipurpose uploader module, so can't send a specific link. As mentioned the fileId goes into the GET request where the ID parameter is required. So just construct a link on your side and use it. I think that is the proper way to do it.

**Comment by shahidhk** [comment]
BTW, what about social login?

**Comment by aqelkp** [comment]
@shahidhk They have already made an account with coord app portal
We'll use the same for erp also

**Comment by shahidhk** [comment]
For website users?

**Comment by aqelkp** [comment]
For all users.

**Comment by shahidhk** [comment]
Website users do not have an account on coord portal

**Comment by chinnichaitanya** [comment]
@shahidhk For website users, we can maintain a separate database right ?

**Comment by deepakpadamata** [comment]
Passport is being used for social login, havent created keys yet. And yeah, won't site users be stored in a separate db? ERP users can of course login with existing accounts.

**Comment by shahidhk** [comment]
Keeping db separate will be pain. Problems starts with events. Coords will
have to update event details which have to be shown in website. How will
you handle this if it's separate db?

Separate db will cause many issues

**Comment by deepakpadamata** [comment]
I mean separate model/table, for visitors. Anyways, we can have social login integrated with the present used model, with some modification for College, Saarang ID, etc.

**Comment by chinnichaitanya** [comment]
@shahidhk I didn't get you. Yes coords will update the data in the events-portal which is entirely different from the website. We are not using the same credentials or anything for the coords to log in to the website.

**Comment by deepakpadamata** [comment]
He thought different db meant a different "database" whereas your intended use was probably a different "collection"("table" in traditional DBs)

**Comment by chinnichaitanya** [comment]
Oh! Yeah. My bad. I meant different collection.

**Comment by shahidhk** [comment]
What we did was a common user table which django uses for auth, and
separate user profile tables for erp user and website user

Do that accordingly

**Comment by chinnichaitanya** [comment]
Right now we don't need to do that. We can have separate collections for website-users and erp-users.
That should not be an issue.

**Comment by deepakpadamata** [comment]
@shahidhk - What would be the advantages of having one auth and two profiles? Apart from reconciling it with Django Auth.

**Comment by shahidhk** [comment]
i don't know how auth works in node or express or whatever you are using,
but in django, there is a default user model where auth us handled
automatically

**Comment by chinnichaitanya** [comment]
It is not the case here. We can create different collections/tables of users. Since the *erp-users* and *website-users* will have a different model, we can create two separate collections. 
There is nothing like default *auth* module here.

**Comment by aqelkp** [comment]
The image should be given in login api
@deepakpadamata  Right now, are you identifying an image file uploaded as a profile pic?

**Comment by chinnichaitanya** [comment]
Right now it will just upload the image.
We need to store it's `id` in the current logged in user. But since we are using the same upload api for other uploads also, we need to make a separate function for storing the `id` in the user profile. That won't be difficult.

**Comment by aqelkp** [comment]
Everything perfect here
