### ISSUE TITLE
Token validity 

### ISSUE THREAD

**Issue by aqelkp** [The-WebOps-Club/erp-2016#13]
Don't change token for a user. Login from app will be done only once

**Comment by deepakpadamata** [comment]
Can you supply a lasting ID which can reliably authenticate the phone as well as the user?
I'm thinking of hashing the Device ID and password together to get a token which will be used for subsequent logins.

**Comment by aqelkp** [comment]
There will be only one login for one user
I can give you a unique device id

**Comment by deepakpadamata** [comment]
Added a new auth API endpoint 
`POST` to /auth/local/mobile
Same details as /auth/local
Will return a token with infinite validity.
To logout, just clear the token on the client side

PS: Will this bring security issues?

**Comment by aqelkp** [comment]
This is how Facebook token works
Native mobile applications using Facebook's SDKs will get long-lived access tokens, good for about 60 days. These tokens will be refreshed once per day when the person using your app makes a request to Facebook's servers. If no requests are made, the token will expire after about 60 days and the person will have to go through the login flow again to get a new token.
