### ISSUE TITLE
User details in login API for mobile

### ISSUE THREAD

**Issue by aqelkp** [The-WebOps-Club/erp-2016#18]
/auth/local/mobile should return user details along with token

**Comment by chinnichaitanya** [comment]
For fetching user details, you can use a different api.

**Comment by aqelkp** [comment]
I want it get from the same api.
Why would make a issue otherwise?

**Comment by chinnichaitanya** [comment]
I thought you didn't know that there is another api for getting user details. 
Can't you make another request and get the details ?

**Comment by aqelkp** [comment]
Why making another extra request and causing delays if i can get everything
from one place
Deepak have already made a separate API for mobile. Can change that one

On Mon, Jun 15, 2015 at 3:07 PM, Chinni Chaitanya <notifications@github.com>
wrote:

> I thought you didn't know that there is another api for getting user
> details.
> Can't you make another request and get the details ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/The-WebOps-Club/erp-2016/issues/18#issuecomment-111997338>
> .
>



-- 
*Aqel Ahammad K P*
Undergraduate Student
Chemical Engineering Department
IIT Madras
Ph: 9176285068, 9633229144

**Comment by shahidhk** [comment]
As a mobile application, we should concentrate on minimising the number of
request as well as reduce the data sent in each request.

If the user can log in, i mean if the credentials are correct, why not send
the profile details itself together.?

But make a separate request for the profile pic etc.
Data and media should never be clubbed together

On 15 June 2015 at 15:09, Aqel Ahammed <notifications@github.com> wrote:

> Why making another extra request and causing delays if i can get everything
> from one place
> Deepak have already made a separate API for mobile. Can change that one
>
> On Mon, Jun 15, 2015 at 3:07 PM, Chinni Chaitanya <
> notifications@github.com>
> wrote:
>
>
> > I thought you didn't know that there is another api for getting user
> > details.
> > Can't you make another request and get the details ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/The-WebOps-Club/erp-2016/issues/18#issuecomment-111997338
> >
> > .
> >
>
>
>
> --
> *Aqel Ahammad K P*
> Undergraduate Student
> Chemical Engineering Department
> IIT Madras
> Ph: 9176285068, 9633229144
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/The-WebOps-Club/erp-2016/issues/18#issuecomment-111998316>
> .
>



-- 
Shahidh K Muhammed
Undergraduate Student
Department of Engineering Design
Indian Institute of Technology Madras
Chennai 600036
Mobile: (+91) 9496362472
http://shahidh.me

**Comment by deepakpadamata** [comment]
Login API done as per requirment.
@shahidhk - pic is sent as a link, it is a separate request only
