### ISSUE TITLE
I am not authorised to post on my wall!!

### ISSUE THREAD

**Issue by aqelkp** [The-WebOps-Club/erp-2016#25]

**Comment by chinnichaitanya** [comment]
@aqelkp Can you tell what is the error ?

**Comment by chinnichaitanya** [comment]
Is it `500` or `404` or `403` ?

**Comment by chinnichaitanya** [comment]
And just now realized, it might be because of https://github.com/The-WebOps-Club/erp-2016/commit/3750948fb360e2cb039c7ccd8c5c8fc1b80f1421 commit.

**Comment by aqelkp** [comment]
404
<img width="931" alt="screen shot 2015-07-08 at 11 41 09 pm" src="https://cloud.githubusercontent.com/assets/8310191/8578191/f5aa41b0-25ca-11e5-9398-64ece20e6a41.png">

**Comment by deepakpadamata** [comment]
That commit is not on the server. @aqelkp  - the destId is not the ID of the wall but rather the ID of the profile/department/subDepartment/group that you want to post to
in this case replace the destId with 55924da076c5a9c360ad6581 and it should work
